### ISSUE TITLE
Manusear erros apropriadamente

### ISSUE THREAD

**Issue by kauefraga** [hiroshimorowaka/esp32-pong-game#1]
Primeiro, parabéns pelo projeto, achei muito bacana :)

Olhando o código, a única coisa que me chamou a atenção foi o uso do `.unwrap()`, que retorna o valor se ele existir e, caso contrário, dá pânico na execução.

O Rust tem os tipos `Option<T>` e `Result<T, E>` para garantir o manuseio apropriado de dois estados: a existência de valor e a ausência de valor (ou presença de erro). Ao utilizar o método `.unwrap()` tu deixa de lidar com a possibilidade de ter um erro ou não ter um valor.

Segue algumas **sugestões** para lidar com a presença de erro ou ausência de valor:

- `.unwrap_or()` - pega o valor ou retorna um valor padrão (ao invés de dar pânico)
- `match` - pattern matching em `Some/Ok` e `None/Err`
  - alternativa: `if let`
  
Não tenho certeza, mas também deve ser possível mapear (`.map()`) os possíveis valores para outros valores.

**Comment by hiroshimorowaka** [comment]
Muito obrigado pelo apoio @kauefraga !

O unwrap eu uso somente quando eu to manuseando os componentes eletrônicos pelo código. 

Caso os componentes eletrônicos necessários não estejam ligados na placa, ele realmente vai crashar o programa. Eu tava pensando em usar algum pattern matching pra lidar com esse tipo de erro, mas como eu iria avisar pro indivíduo que os componentes estão ligados errado ou a pessoa esqueceu de colocar? Eu não consegui pensar em nenhuma forma, mas se você conseguir pensar em alguma, sua sugestão será muito bem vinda. 

Eu acho que para os botões, como eles só tem dois estados (ligado ou desligado) dá pra usar o "unwrap_or()". Porque mesmo que os botões não estejam conectados apropriadamente na placa, não vale a pena crashar o programa. O que você acha?

**Comment by kauefraga** [comment]
No caso dos botões, é isso aí. Sempre que possível, evita crashar a execução.

Sobre o manuseio dos componentes eletrônicos, esqueci que não tem a biblioteca padrão (`std::io::Stdout` e `println!`), acho que nesse caso faz sentido crashar se os componentes não estiverem ligados ou mal conectados.

**Comment by hiroshimorowaka** [comment]
Muito obrigado pela ajuda @kauefraga !

Fiz a alteração nos botões!
